[package]
name = "rust_pong"
version = "0.1.0"
authors = ["Douglas Anderson <hockeybuggy@gmail.com>"]

[dependencies]
rand = "0.3"

piston = "*"
piston2d-graphics = "*"
piston2d-opengl_graphics = "*"
pistoncore-glutin_window = "*"
